<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $tables = [
            'order_item_refund_events',
            'cart_items',
            'wallet_transactions',
            'reports',
            'questions',
            'order_items',
            'orders',
            'user_addresses',
            'items',
            'users',
        ];

        DB::transaction(function () use ($tables): void {
            Schema::disableForeignKeyConstraints();

            foreach ($tables as $table) {
                DB::table($table)->delete();
            }

            Schema::enableForeignKeyConstraints();

            DB::table('users')->insert([
                [
                    'id' => 1,
                    'name' => 'Tan SuperAdmin',
                    'email' => 'tan@cloth.com',
                    'email_verified_at' => '2026-04-02 07:37:21',
                    'phone' => null,
                    'password' => '$2y$12$Q60yJRsdF24/yxj53MaU.OE4Fs9wQjhb9bN4s33dCBskvC4x.CWba',
                    'role' => 'superadmin',
                    'balance' => 0,
                    'remember_token' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'deleted_at' => null,
                ],
                [
                    'id' => 2,
                    'name' => 'Admin 1',
                    'email' => 'admin@cloth.com',
                    'email_verified_at' => '2026-04-02 07:37:21',
                    'phone' => null,
                    'password' => '$2y$12$7jpKNF1EzroJ4ViJdgNqs.eEXP1Wvne2.U2GVmMt42s.Og6xVX.3i',
                    'role' => 'admin',
                    'balance' => 0,
                    'remember_token' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'deleted_at' => null,
                ],
                [
                    'id' => 3,
                    'name' => 'Nakarin',
                    'email' => 'sbkyajeg4312@gmail.com',
                    'email_verified_at' => '2026-04-02 07:37:21',
                    'phone' => null,
                    'password' => '$2y$12$0bj8Xc0HAdZIc8qDzrcOne3Xey4MLC.YT.P7kYZjv/fyT.jHoiqEC',
                    'role' => 'user',
                    'balance' => 2550,
                    'remember_token' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 10:39:17',
                    'deleted_at' => null,
                ],
                [
                    'id' => 4,
                    'name' => 'May Customer',
                    'email' => 'may@cloth.com',
                    'email_verified_at' => '2026-04-02 07:37:21',
                    'phone' => null,
                    'password' => '$2y$12$x26dun1zhsbbT4YHrAm8uubitgHCaY0Q3AU4201VyAcRT5A7QSt4y',
                    'role' => 'user',
                    'balance' => 3310,
                    'remember_token' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 09:17:31',
                    'deleted_at' => null,
                ],
                [
                    'id' => 5,
                    'name' => 'Tan Nakarin',
                    'email' => 'toruplaytube@gmail.com',
                    'email_verified_at' => null,
                    'phone' => null,
                    'password' => '$2y$12$mntMij0nW.mgXD92gJFAfOsvSL.ux/.VsBWrsAwISgknWLrZ8MjnC',
                    'role' => 'user',
                    'balance' => 4000,
                    'remember_token' => null,
                    'created_at' => '2026-04-02 07:43:44',
                    'updated_at' => '2026-04-02 07:43:51',
                    'deleted_at' => null,
                ],
                [
                    'id' => 6,
                    'name' => 'Somchai',
                    'email' => 'somchai@cloth.com',
                    'email_verified_at' => null,
                    'phone' => null,
                    'password' => '$2y$12$keZ.znENpKjXrLVPd5iV5OVM0gKCOg0osJw/3FGavb3ZbgVjT1ltO',
                    'role' => 'user',
                    'balance' => 2000,
                    'remember_token' => null,
                    'created_at' => '2026-04-02 09:01:43',
                    'updated_at' => '2026-04-02 10:39:40',
                    'deleted_at' => null,
                ],
            ]);

            DB::table('items')->insert([
                [
                    'id' => 1,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'Fresh Apple',
                    'description' => 'It is very fresh and sweet (Apple replica. Please do not eat)',
                    'price' => 40,
                    'stock' => 69,
                    'image_path' => 'items/apple.jpg',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 10:24:25',
                    'deleted_at' => null,
                ],
                [
                    'id' => 2,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'XL KU CS T-Shirt',
                    'description' => 'Standard issue CS shirt. 100% Cotton.',
                    'price' => 250,
                    'stock' => 48,
                    'image_path' => 'items/black_cs_shirt.png',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 10:06:09',
                    'deleted_at' => null,
                ],
                [
                    'id' => 3,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'XS Tech Faculty Hoodie',
                    'description' => 'Warm polyester hoodie for the cold labs.',
                    'price' => 600,
                    'stock' => 19,
                    'image_path' => 'items/black_cs_hoodie.png',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 09:17:31',
                    'deleted_at' => null,
                ],
                [
                    'id' => 4,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'Laptop Sticker Pack',
                    'description' => 'Vinyl stickers for your ThinkPad.',
                    'price' => 50,
                    'stock' => 100,
                    'image_path' => 'items/cute_sticker.png',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'deleted_at' => null,
                ],
                [
                    'id' => 5,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'Chicken Sticker Pack',
                    'description' => 'Nice Chicken stickers for your accessories.',
                    'price' => 2000,
                    'stock' => 4,
                    'image_path' => 'items/chicken_sticker.jpg',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 10:07:18',
                    'deleted_at' => null,
                ],
                [
                    'id' => 6,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'CS Baseball Cap',
                    'description' => 'Lightweight cap with embroidered CS logo.',
                    'price' => 320,
                    'stock' => 40,
                    'image_path' => 'items/green_csku_cap.png',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'deleted_at' => null,
                ],
                [
                    'id' => 7,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'Chicken',
                    'description' => 'grilled chicken',
                    'price' => 50,
                    'stock' => 200,
                    'image_path' => 'items/w0VU7QB3iJ4KCxInTPt02MGXts7SOAAba1xMwQKN.png',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 10:17:42',
                    'updated_at' => '2026-04-02 10:17:42',
                    'deleted_at' => null,
                ],
                [
                    'id' => 8,
                    'created_by_id' => 2,
                    'updated_by' => null,
                    'name' => 'Rare WW2 Shirt (Good Condition)',
                    'description' => 'Worn by the famous mustache man',
                    'price' => 10000000,
                    'stock' => 1,
                    'image_path' => 'items/RSiujx7cEHAGp4SbHDoWA5zKgJTtMFwuhhBVZQlp.png',
                    'is_active' => 1,
                    'created_at' => '2026-04-02 11:16:34',
                    'updated_at' => '2026-04-02 11:21:04',
                    'deleted_at' => null,
                ],
            ]);

            DB::table('user_addresses')->insert([
                [
                    'id' => 1,
                    'user_id' => 3,
                    'label' => 'Home',
                    'recipient_name' => 'Test Customer 1',
                    'phone' => '0812345678',
                    'line_1' => '123 Ngamwongwan Rd',
                    'line_2' => 'Chatuchak',
                    'district' => 'Chatuchak',
                    'province' => 'Bangkok',
                    'postal_code' => '10900',
                    'country' => 'Thailand',
                    'is_default' => 0,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 10:06:09',
                ],
                [
                    'id' => 2,
                    'user_id' => 4,
                    'label' => 'Dorm',
                    'recipient_name' => 'May Customer',
                    'phone' => '0898765432',
                    'line_1' => '77 Dormitory Road',
                    'line_2' => 'Room 908',
                    'district' => 'Bang Khen',
                    'province' => 'Bangkok',
                    'postal_code' => '10220',
                    'country' => 'Thailand',
                    'is_default' => 1,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                ],
                [
                    'id' => 4,
                    'user_id' => 3,
                    'label' => 'Home',
                    'recipient_name' => 'Nakarin',
                    'phone' => '0889105121',
                    'line_1' => 'Nakarin Street',
                    'line_2' => null,
                    'district' => 'Bang Khaen',
                    'province' => 'Bangkok',
                    'postal_code' => '10500',
                    'country' => 'Thailand',
                    'is_default' => 1,
                    'created_at' => '2026-04-02 10:06:09',
                    'updated_at' => '2026-04-02 10:06:09',
                ],
            ]);

            DB::table('questions')->insert([
                [
                    'id' => 1,
                    'item_id' => 1,
                    'asker_id' => 3,
                    'asker_name' => 'Test Customer 1',
                    'admin_id' => 2,
                    'admin_name' => 'Admin 1',
                    'question_text' => 'Is this cotton?',
                    'answer_text' => 'idk',
                    'score_cached' => 0,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'deleted_at' => null,
                ],
                [
                    'id' => 2,
                    'item_id' => 1,
                    'asker_id' => 3,
                    'asker_name' => 'Test Customer 1',
                    'admin_id' => null,
                    'admin_name' => null,
                    'question_text' => 'Is this big?',
                    'answer_text' => null,
                    'score_cached' => 0,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 09:12:39',
                    'deleted_at' => null,
                ],
                [
                    'id' => 3,
                    'item_id' => 1,
                    'asker_id' => 3,
                    'asker_name' => 'Test Customer 1',
                    'admin_id' => null,
                    'admin_name' => null,
                    'question_text' => 'Can I eat this?',
                    'answer_text' => null,
                    'score_cached' => 0,
                    'created_at' => '2026-04-02 09:08:49',
                    'updated_at' => '2026-04-02 10:14:05',
                    'deleted_at' => null,
                ],
                [
                    'id' => 4,
                    'item_id' => 1,
                    'asker_id' => 3,
                    'asker_name' => 'Test Customer 1',
                    'admin_id' => null,
                    'admin_name' => null,
                    'question_text' => 'Is this fresh?',
                    'answer_text' => null,
                    'score_cached' => 0,
                    'created_at' => '2026-04-02 10:09:56',
                    'updated_at' => '2026-04-02 10:15:52',
                    'deleted_at' => null,
                ],
            ]);

            DB::table('reports')->insert([
                [
                    'id' => 1,
                    'reporter_id' => 3,
                    'reporter_name' => 'Test Customer 1',
                    'admin_id' => 2,
                    'admin_name' => 'Admin 1',
                    'question_id' => 1,
                    'question_text_snapshot' => "Is this cotton?",
                    'answer_text_snapshot' => 'idk',
                    'reason' => "Doesn't answer the question",
                    'status' => 'dismissed',
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:38:36',
                ],
                [
                    'id' => 2,
                    'reporter_id' => 3,
                    'reporter_name' => 'Test Customer 1',
                    'admin_id' => 2,
                    'admin_name' => 'Admin 1',
                    'question_id' => 2,
                    'question_text_snapshot' => 'Is this big?',
                    'answer_text_snapshot' => 'yes like yo mama',
                    'reason' => 'Rude answer',
                    'status' => 'dismissed',
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:38:38',
                ],
                [
                    'id' => 3,
                    'reporter_id' => 3,
                    'reporter_name' => 'Test Customer 1',
                    'admin_id' => 2,
                    'admin_name' => 'Admin 1',
                    'question_id' => 2,
                    'question_text_snapshot' => 'Is this big?',
                    'answer_text_snapshot' => 'yes like yo mama',
                    'reason' => 'so rudeeeeeee',
                    'status' => 'resolved',
                    'created_at' => '2026-04-02 07:41:58',
                    'updated_at' => '2026-04-02 07:42:09',
                ],
                [
                    'id' => 4,
                    'reporter_id' => 3,
                    'reporter_name' => 'Test Customer 1',
                    'admin_id' => 2,
                    'admin_name' => 'Admin 1',
                    'question_id' => 1,
                    'question_text_snapshot' => 'Is this cotton?',
                    'answer_text_snapshot' => 'idk',
                    'reason' => 'Why even answer? Fire this person.',
                    'status' => 'dismissed',
                    'created_at' => '2026-04-02 08:57:06',
                    'updated_at' => '2026-04-02 10:13:50',
                ],
                [
                    'id' => 5,
                    'reporter_id' => 3,
                    'reporter_name' => 'Test Customer 1',
                    'admin_id' => 2,
                    'admin_name' => 'Admin 1',
                    'question_id' => 3,
                    'question_text_snapshot' => 'Can I eat this?',
                    'answer_text_snapshot' => 'Absolutely not',
                    'reason' => 'Not polite enough',
                    'status' => 'resolved',
                    'created_at' => '2026-04-02 10:10:37',
                    'updated_at' => '2026-04-02 10:14:05',
                ],
                [
                    'id' => 6,
                    'reporter_id' => 3,
                    'reporter_name' => 'Test Customer 1',
                    'admin_id' => 2,
                    'admin_name' => 'Admin 1',
                    'question_id' => 4,
                    'question_text_snapshot' => 'Is this fresh?',
                    'answer_text_snapshot' => 'No.',
                    'reason' => 'Not appropraite',
                    'status' => 'resolved',
                    'created_at' => '2026-04-02 10:15:34',
                    'updated_at' => '2026-04-02 10:15:52',
                ],
            ]);

            DB::table('orders')->insert([
                [
                    'id' => 1,
                    'order_number' => '260401PN10TSH1',
                    'buyer_id' => 3,
                    'status' => 'pending',
                    'total_price' => 500,
                    'shipping_address_id' => 1,
                    'shipping_address' => '123 Ngamwongwan Rd, Chatuchak, Bangkok, 10900, Thailand',
                    'shipping_address_snapshot' => '{"label":"Home","recipient_name":"Test Customer 1","phone":"0812345678","line_1":"123 Ngamwongwan Rd","line_2":"Chatuchak","district":"Chatuchak","province":"Bangkok","postal_code":"10900","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => null,
                    'cancelled_at' => null,
                    'refund_requested_at' => null,
                    'refunded_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'delivery_method' => null,
                    'delivery_method_label' => null,
                ],
                [
                    'id' => 2,
                    'order_number' => '260401RF21HOD9',
                    'buyer_id' => 3,
                    'status' => 'refunding',
                    'total_price' => 600,
                    'shipping_address_id' => 1,
                    'shipping_address' => 'Kasetsart University, Lab 404',
                    'shipping_address_snapshot' => '{"label":"Campus","recipient_name":"Test Customer 1","phone":"0812345678","line_1":"Kasetsart University, Lab 404","line_2":null,"district":"Chatuchak","province":"Bangkok","postal_code":"10900","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => null,
                    'cancelled_at' => null,
                    'refund_requested_at' => '2026-04-02 07:37:21',
                    'refunded_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'delivery_method' => null,
                    'delivery_method_label' => null,
                ],
                [
                    'id' => 3,
                    'order_number' => '260401PR32APP7',
                    'buyer_id' => 3,
                    'status' => 'refunding',
                    'total_price' => 750,
                    'shipping_address_id' => 1,
                    'shipping_address' => '123 Ngamwongwan Rd, Chatuchak, Bangkok, 10900, Thailand',
                    'shipping_address_snapshot' => '{"label":"Home","recipient_name":"Test Customer 1","phone":"0812345678","line_1":"123 Ngamwongwan Rd","line_2":"Chatuchak","district":"Chatuchak","province":"Bangkok","postal_code":"10900","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => '2026-03-27 07:37:21',
                    'cancelled_at' => null,
                    'refund_requested_at' => '2026-04-02 09:45:07',
                    'refunded_at' => '2026-03-31 07:37:21',
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 09:45:07',
                    'delivery_method' => null,
                    'delivery_method_label' => null,
                ],
                [
                    'id' => 4,
                    'order_number' => '260401SH43STK8',
                    'buyer_id' => 4,
                    'status' => 'shipped',
                    'total_price' => 640,
                    'shipping_address_id' => 2,
                    'shipping_address' => '77 Dormitory Road, Room 908, Bang Khen, Bangkok, 10220, Thailand',
                    'shipping_address_snapshot' => '{"label":"Dorm","recipient_name":"May Customer","phone":"0898765432","line_1":"77 Dormitory Road","line_2":"Room 908","district":"Bang Khen","province":"Bangkok","postal_code":"10220","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => '2026-04-01 07:37:21',
                    'cancelled_at' => null,
                    'refund_requested_at' => null,
                    'refunded_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'delivery_method' => null,
                    'delivery_method_label' => null,
                ],
                [
                    'id' => 5,
                    'order_number' => '260401RF54STK2',
                    'buyer_id' => 4,
                    'status' => 'refunding',
                    'total_price' => 150,
                    'shipping_address_id' => 2,
                    'shipping_address' => '77 Dormitory Road, Room 908, Bang Khen, Bangkok, 10220, Thailand',
                    'shipping_address_snapshot' => '{"label":"Dorm","recipient_name":"May Customer","phone":"0898765432","line_1":"77 Dormitory Road","line_2":"Room 908","district":"Bang Khen","province":"Bangkok","postal_code":"10220","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => '2026-03-29 07:37:21',
                    'cancelled_at' => null,
                    'refund_requested_at' => '2026-04-01 23:37:21',
                    'refunded_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'delivery_method' => null,
                    'delivery_method_label' => null,
                ],
                [
                    'id' => 6,
                    'order_number' => '260401RF65CAP4',
                    'buyer_id' => 4,
                    'status' => 'refunded',
                    'total_price' => 320,
                    'shipping_address_id' => 2,
                    'shipping_address' => '77 Dormitory Road, Room 908, Bang Khen, Bangkok, 10220, Thailand',
                    'shipping_address_snapshot' => '{"label":"Dorm","recipient_name":"May Customer","phone":"0898765432","line_1":"77 Dormitory Road","line_2":"Room 908","district":"Bang Khen","province":"Bangkok","postal_code":"10220","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => '2026-03-23 07:37:21',
                    'cancelled_at' => null,
                    'refund_requested_at' => '2026-03-25 07:37:21',
                    'refunded_at' => '2026-03-26 07:37:21',
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'delivery_method' => null,
                    'delivery_method_label' => null,
                ],
                [
                    'id' => 7,
                    'order_number' => '260402ZX92DC5A',
                    'buyer_id' => 4,
                    'status' => 'pending',
                    'total_price' => 890,
                    'shipping_address_id' => 2,
                    'shipping_address' => 'May Customer, 0898765432, 77 Dormitory Road, Room 908, Bang Khen, Bangkok, 10220, Thailand',
                    'shipping_address_snapshot' => '{"label":"Dorm","recipient_name":"May Customer","phone":"0898765432","line_1":"77 Dormitory Road","line_2":"Room 908","district":"Bang Khen","province":"Bangkok","postal_code":"10220","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => null,
                    'cancelled_at' => null,
                    'refund_requested_at' => null,
                    'refunded_at' => null,
                    'created_at' => '2026-04-02 09:17:31',
                    'updated_at' => '2026-04-02 09:17:31',
                    'delivery_method' => 'thunder_express',
                    'delivery_method_label' => 'Thunder Express',
                ],
                [
                    'id' => 8,
                    'order_number' => '260402BM79ALRI',
                    'buyer_id' => 3,
                    'status' => 'pending',
                    'total_price' => 250,
                    'shipping_address_id' => 4,
                    'shipping_address' => 'Nakarin, 0889105121, Nakarin Street, Bang Khaen, Bangkok, 10500, Thailand',
                    'shipping_address_snapshot' => '{"label":"Home","recipient_name":"Nakarin","phone":"0889105121","line_1":"Nakarin Street","line_2":null,"district":"Bang Khaen","province":"Bangkok","postal_code":"10500","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => null,
                    'shipped_at' => null,
                    'cancelled_at' => null,
                    'refund_requested_at' => null,
                    'refunded_at' => null,
                    'created_at' => '2026-04-02 10:06:09',
                    'updated_at' => '2026-04-02 10:06:09',
                    'delivery_method' => 'jt_express',
                    'delivery_method_label' => 'J&T Express',
                ],
                [
                    'id' => 9,
                    'order_number' => '260402OK50EPVX',
                    'buyer_id' => 3,
                    'status' => 'partially_refunded',
                    'total_price' => 3400,
                    'shipping_address_id' => 4,
                    'shipping_address' => 'Nakarin, 0889105121, Nakarin Street, Bang Khaen, Bangkok, 10500, Thailand',
                    'shipping_address_snapshot' => '{"label":"Home","recipient_name":"Nakarin","phone":"0889105121","line_1":"Nakarin Street","line_2":null,"district":"Bang Khaen","province":"Bangkok","postal_code":"10500","country":"Thailand"}',
                    'admin_shipped_id' => null,
                    'admin_refunded_id' => 2,
                    'shipped_at' => '2026-04-02 10:18:38',
                    'cancelled_at' => null,
                    'refund_requested_at' => '2026-04-02 10:23:49',
                    'refunded_at' => '2026-04-02 10:24:25',
                    'created_at' => '2026-04-02 10:07:18',
                    'updated_at' => '2026-04-02 10:24:25',
                    'delivery_method' => 'kerry_express',
                    'delivery_method_label' => 'Kerry Express',
                ],
            ]);

            DB::table('order_items')->insert([
                [
                    'id' => 1,
                    'order_id' => 1,
                    'item_id' => 2,
                    'quantity' => 2,
                    'price_at_purchase' => 250,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => null,
                    'refund_reason_detail' => null,
                    'refund_issue_description' => null,
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => null,
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 2,
                    'order_id' => 2,
                    'item_id' => 3,
                    'quantity' => 1,
                    'price_at_purchase' => 600,
                    'refund_requested_quantity' => 1,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => 'damaged_item',
                    'refund_reason_detail' => null,
                    'refund_issue_description' => 'The hoodie zipper arrived broken and the front pocket seam is torn.',
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => '2026-04-02 07:37:21',
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 3,
                    'order_id' => 3,
                    'item_id' => 2,
                    'quantity' => 3,
                    'price_at_purchase' => 250,
                    'refund_requested_quantity' => 1,
                    'refunded_quantity' => 1,
                    'refund_reason_code' => 'damaged_item',
                    'refund_reason_detail' => null,
                    'refund_issue_description' => "It's all torn up !!!",
                    'refund_evidence_image_path' => 'refund-evidence/cjecFw31gbFsvnelBiaUue7qSji9l1k3Bx3ySjaT.png',
                    'refund_requested_at' => '2026-04-02 09:45:07',
                    'refund_approved_at' => '2026-03-31 07:37:21',
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 09:45:07',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 4,
                    'order_id' => 4,
                    'item_id' => 6,
                    'quantity' => 2,
                    'price_at_purchase' => 320,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => null,
                    'refund_reason_detail' => null,
                    'refund_issue_description' => null,
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => null,
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 5,
                    'order_id' => 5,
                    'item_id' => 4,
                    'quantity' => 3,
                    'price_at_purchase' => 50,
                    'refund_requested_quantity' => 1,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => 'other',
                    'refund_reason_detail' => 'Wrong design',
                    'refund_issue_description' => 'One of the sticker sheets has the wrong artwork printed on it.',
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => '2026-04-01 23:37:21',
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 6,
                    'order_id' => 6,
                    'item_id' => 6,
                    'quantity' => 1,
                    'price_at_purchase' => 320,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 1,
                    'refund_reason_code' => 'wrong_item',
                    'refund_reason_detail' => null,
                    'refund_issue_description' => 'Received the wrong hat color and support approved the refund.',
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => '2026-03-25 07:37:21',
                    'refund_approved_at' => '2026-03-26 07:37:21',
                    'created_at' => '2026-04-02 07:37:21',
                    'updated_at' => '2026-04-02 07:37:21',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 7,
                    'order_id' => 7,
                    'item_id' => 1,
                    'quantity' => 1,
                    'price_at_purchase' => 40,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => null,
                    'refund_reason_detail' => null,
                    'refund_issue_description' => null,
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => null,
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 09:17:31',
                    'updated_at' => '2026-04-02 09:17:31',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 8,
                    'order_id' => 7,
                    'item_id' => 2,
                    'quantity' => 1,
                    'price_at_purchase' => 250,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => null,
                    'refund_reason_detail' => null,
                    'refund_issue_description' => null,
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => null,
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 09:17:31',
                    'updated_at' => '2026-04-02 09:17:31',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 9,
                    'order_id' => 7,
                    'item_id' => 3,
                    'quantity' => 1,
                    'price_at_purchase' => 600,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => null,
                    'refund_reason_detail' => null,
                    'refund_issue_description' => null,
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => null,
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 09:17:31',
                    'updated_at' => '2026-04-02 09:17:31',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 10,
                    'order_id' => 8,
                    'item_id' => 2,
                    'quantity' => 1,
                    'price_at_purchase' => 250,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => null,
                    'refund_reason_detail' => null,
                    'refund_issue_description' => null,
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => null,
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 10:06:09',
                    'updated_at' => '2026-04-02 10:06:09',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 11,
                    'order_id' => 9,
                    'item_id' => 1,
                    'quantity' => 35,
                    'price_at_purchase' => 40,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 5,
                    'refund_reason_code' => 'damaged_item',
                    'refund_reason_detail' => null,
                    'refund_issue_description' => 'Rotten apple',
                    'refund_evidence_image_path' => 'refund-evidence/LKPwOyd4FoYnr1t02GuzBEwaJLbIv6wQAPkO4vff.png',
                    'refund_requested_at' => '2026-04-02 10:23:49',
                    'refund_approved_at' => '2026-04-02 10:24:25',
                    'created_at' => '2026-04-02 10:07:18',
                    'updated_at' => '2026-04-02 10:24:25',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
                [
                    'id' => 12,
                    'order_id' => 9,
                    'item_id' => 5,
                    'quantity' => 1,
                    'price_at_purchase' => 2000,
                    'refund_requested_quantity' => 0,
                    'refunded_quantity' => 0,
                    'refund_reason_code' => null,
                    'refund_reason_detail' => null,
                    'refund_issue_description' => null,
                    'refund_evidence_image_path' => null,
                    'refund_requested_at' => null,
                    'refund_approved_at' => null,
                    'created_at' => '2026-04-02 10:07:18',
                    'updated_at' => '2026-04-02 10:07:18',
                    'refund_dismissed_quantity' => 0,
                    'refund_dismissed_at' => null,
                ],
            ]);

            DB::table('wallet_transactions')->insert([
                [
                    'id' => 1,
                    'user_id' => 5,
                    'type' => 'top_up',
                    'provider' => 'scb_easy',
                    'status' => 'completed',
                    'amount' => 2000,
                    'balance_before' => 0,
                    'balance_after' => 2000,
                    'reference' => 'TOPUP-20260402-8B3MQQ',
                    'note' => null,
                    'completed_at' => '2026-04-02 07:43:51',
                    'created_at' => '2026-04-02 07:43:51',
                    'updated_at' => '2026-04-02 07:43:51',
                ],
                [
                    'id' => 2,
                    'user_id' => 5,
                    'type' => 'top_up',
                    'provider' => 'scb_easy',
                    'status' => 'completed',
                    'amount' => 2000,
                    'balance_before' => 2000,
                    'balance_after' => 4000,
                    'reference' => 'TOPUP-20260402-8KFSRB',
                    'note' => null,
                    'completed_at' => '2026-04-02 07:43:51',
                    'created_at' => '2026-04-02 07:43:51',
                    'updated_at' => '2026-04-02 07:43:51',
                ],
                [
                    'id' => 3,
                    'user_id' => 3,
                    'type' => 'top_up',
                    'provider' => 'credit_debit_card',
                    'status' => 'completed',
                    'amount' => 1000,
                    'balance_before' => 1350,
                    'balance_after' => 2350,
                    'reference' => 'TOPUP-20260402-TEGNXA',
                    'note' => 'Card ending in 8263',
                    'completed_at' => '2026-04-02 10:09:23',
                    'created_at' => '2026-04-02 10:09:23',
                    'updated_at' => '2026-04-02 10:09:23',
                ],
                [
                    'id' => 4,
                    'user_id' => 6,
                    'type' => 'top_up',
                    'provider' => 'scb_easy',
                    'status' => 'completed',
                    'amount' => 2000,
                    'balance_before' => 0,
                    'balance_after' => 2000,
                    'reference' => 'TOPUP-20260402-FAOUAS',
                    'note' => null,
                    'completed_at' => '2026-04-02 10:39:40',
                    'created_at' => '2026-04-02 10:39:40',
                    'updated_at' => '2026-04-02 10:39:40',
                ],
            ]);

            DB::table('cart_items')->insert([
                [
                    'user_id' => 6,
                    'item_id' => 1,
                    'quantity' => 5,
                    'created_at' => '2026-04-02 10:43:20',
                    'updated_at' => '2026-04-02 10:43:25',
                ],
                [
                    'user_id' => 6,
                    'item_id' => 4,
                    'quantity' => 1,
                    'created_at' => '2026-04-02 10:44:11',
                    'updated_at' => '2026-04-02 10:44:11',
                ],
            ]);

            DB::table('order_item_refund_events')->insert([
                [
                    'id' => 1,
                    'order_item_id' => 3,
                    'event_type' => 'requested',
                    'quantity' => 1,
                    'reason_code' => 'damaged_item',
                    'reason_detail' => null,
                    'issue_description' => "It's all torn up !!!",
                    'evidence_image_path' => 'refund-evidence/cjecFw31gbFsvnelBiaUue7qSji9l1k3Bx3ySjaT.png',
                    'acted_by_user_id' => 3,
                    'happened_at' => '2026-04-02 09:45:07',
                    'created_at' => '2026-04-02 09:45:07',
                    'updated_at' => '2026-04-02 09:45:07',
                ],
                [
                    'id' => 2,
                    'order_item_id' => 11,
                    'event_type' => 'requested',
                    'quantity' => 5,
                    'reason_code' => 'damaged_item',
                    'reason_detail' => null,
                    'issue_description' => 'Rotten apple',
                    'evidence_image_path' => 'refund-evidence/LKPwOyd4FoYnr1t02GuzBEwaJLbIv6wQAPkO4vff.png',
                    'acted_by_user_id' => 3,
                    'happened_at' => '2026-04-02 10:23:49',
                    'created_at' => '2026-04-02 10:23:49',
                    'updated_at' => '2026-04-02 10:23:49',
                ],
                [
                    'id' => 3,
                    'order_item_id' => 11,
                    'event_type' => 'approved',
                    'quantity' => 5,
                    'reason_code' => 'damaged_item',
                    'reason_detail' => null,
                    'issue_description' => 'Rotten apple',
                    'evidence_image_path' => 'refund-evidence/LKPwOyd4FoYnr1t02GuzBEwaJLbIv6wQAPkO4vff.png',
                    'acted_by_user_id' => 2,
                    'happened_at' => '2026-04-02 10:24:25',
                    'created_at' => '2026-04-02 10:24:25',
                    'updated_at' => '2026-04-02 10:24:25',
                ],
            ]);
        });
    }
}
